// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fginxqrywvyrvcmooqci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaW54cXJ5d3Z5cnZjbW9vcWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjMzMDEsImV4cCI6MjA1ODI5OTMwMX0.W0ImcbpjG8cqXZRyqw5xD1czX-sDir9rxrfBjviO31A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);